/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author proxc
 */

public class dashboard extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private ImageIcon format=null;

    /**
     * Creates new form Home15
     */
    
    //variable to reserve data to bypass to other form to memorize
    String sendUser;
    String sendPassword;
    
    public dashboard() {
        //initComponents();
        //conn = uapDB.connectDB();
        
    }
    
    
    
    dashboard(String auser, String apass) throws SQLException
    {
        initComponents();
        
        conn = uapDB.connectDB();      //database connection
        USER.setText(auser);
        String user = auser;
        //String email = aemail;
        String password = apass;
        
        sendUser=user;
        sendPassword=password;
        
        System.out.println(auser+"\n"+apass);
        
//        //back page mouse clicked
//        setLblColor(btnDepartment);
//        resetLblColor(btnFaculty);
//        resetLblColor(btnHome);
//        resetLblColor(btnStudent);
//        departmentPanel.setVisible(true);
//        FacultyPanel.setVisible(false);
//        HomePanel.setVisible(false);
//        StudentPanel.setVisible(false);

        
        //Query to set user image into admin panel
        try 
        {
            String sqli="select photo from admin where username='"+user+"'";
            pst = conn.prepareStatement(sqli);
            System.out.println("Success");
            rs = pst.executeQuery();
            if(rs.next())
            {
                
                byte[] imagedata = rs.getBytes("photo");
                format = new ImageIcon(imagedata);
                Image mm = format.getImage();
                Image img2 = mm.getScaledInstance(USERIMAGE.getWidth(),USERIMAGE.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(img2);
                USERIMAGE.setIcon(image);
                System.out.println("Image::::"+image);
                
            }
        } catch (SQLException e)
        {
                JOptionPane.showMessageDialog(null,"Failed to retrive image");
        }
        
        
        ///
        
        ///Query to retrive Email and phone
        try 
        {
            String sqli="select name, email, phone from admin where username='"+user+"'";
            pst = conn.prepareStatement(sqli);
            System.out.println("Success");
            rs = pst.executeQuery();
            if(rs.next())
            {
                String eMail = rs.getString("email");
                String pHone = rs.getString("phone");
                String nAme = rs.getString("name");
                
                emaillv.setText(eMail);
                namelvl.setText(nAme);
                phonelvl.setText(pHone);
                
            }
        } catch (SQLException e)
        {
                JOptionPane.showMessageDialog(null,"Failed to retrive email");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnFaculty = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnStudent = new javax.swing.JLabel();
        USER = new javax.swing.JLabel();
        USERIMAGE = new javax.swing.JLabel();
        logout = new keeptoo.KButton();
        btnDepartment = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        hmpnl = new javax.swing.JPanel();
        btnStudent4 = new javax.swing.JLabel();
        enrollF = new javax.swing.JButton();
        enrollS = new javax.swing.JButton();
        enrollA = new javax.swing.JButton();
        enroll = new javax.swing.JButton();
        phonelvl = new javax.swing.JLabel();
        emaillv = new javax.swing.JLabel();
        namelvl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        StudentPanel = new javax.swing.JPanel();
        stupnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FacultyPanel = new javax.swing.JPanel();
        fclpnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        departmentPanel = new javax.swing.JPanel();
        dptpnl = new javax.swing.JPanel();
        btnCE = new javax.swing.JButton();
        btnENG = new javax.swing.JButton();
        btnEEE = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnLAW = new javax.swing.JButton();
        btnBBA = new javax.swing.JButton();
        btnCSE = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCourses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 51, 102));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(842, 200));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseMoved(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UAP");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Panel");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        btnHome.setBackground(new java.awt.Color(51, 0, 204));
        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setOpaque(true);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 146, 30));

        btnFaculty.setBackground(new java.awt.Color(51, 102, 255));
        btnFaculty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnFaculty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFaculty.setText("Faculty");
        btnFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFaculty.setOpaque(true);
        btnFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacultyMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 146, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 65, 48));

        btnStudent.setBackground(new java.awt.Color(51, 102, 255));
        btnStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStudent.setText("Student");
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.setOpaque(true);
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 146, 30));

        USER.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        USER.setForeground(new java.awt.Color(51, 0, 204));
        kGradientPanel1.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 30));
        kGradientPanel1.add(USERIMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 80));

        logout.setText("Log Out");
        logout.setkBorderRadius(50);
        logout.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        logout.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        logout.setkHoverStartColor(new java.awt.Color(255, 204, 204));
        logout.setkSelectedColor(new java.awt.Color(255, 0, 51));
        logout.setkStartColor(new java.awt.Color(204, 204, 204));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        kGradientPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 20));

        btnDepartment.setBackground(new java.awt.Color(51, 102, 255));
        btnDepartment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnDepartment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDepartment.setText("Department");
        btnDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepartment.setOpaque(true);
        btnDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepartmentMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 146, 30));

        main.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 230));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setPreferredSize(new java.awt.Dimension(842, 308));
        home.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setMaximumSize(new java.awt.Dimension(842, 308));
        HomePanel.setMinimumSize(new java.awt.Dimension(842, 308));
        HomePanel.setPreferredSize(new java.awt.Dimension(842, 308));

        hmpnl.setBackground(new java.awt.Color(255, 255, 255));
        hmpnl.setMaximumSize(new java.awt.Dimension(842, 308));
        hmpnl.setMinimumSize(new java.awt.Dimension(842, 308));
        hmpnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hmpnlMouseMoved(evt);
            }
        });
        hmpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudent4.setBackground(new java.awt.Color(255, 255, 255));
        btnStudent4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnStudent4.setForeground(new java.awt.Color(51, 0, 102));
        btnStudent4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStudent4.setText("Profile");
        btnStudent4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 153)));
        btnStudent4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStudent4.setOpaque(true);
        hmpnl.add(btnStudent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, 200, 30));

        enrollF.setBackground(new java.awt.Color(51, 0, 255));
        enrollF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollF.setForeground(new java.awt.Color(255, 255, 255));
        enrollF.setText("Faculty");
        enrollF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enrollF.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enrollFMouseMoved(evt);
            }
        });
        enrollF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollFActionPerformed(evt);
            }
        });
        hmpnl.add(enrollF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 90));

        enrollS.setBackground(new java.awt.Color(51, 0, 255));
        enrollS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollS.setForeground(new java.awt.Color(255, 255, 255));
        enrollS.setText("Student");
        enrollS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enrollS.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enrollSMouseMoved(evt);
            }
        });
        enrollS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollSActionPerformed(evt);
            }
        });
        hmpnl.add(enrollS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 100, 90));

        enrollA.setBackground(new java.awt.Color(51, 0, 255));
        enrollA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollA.setForeground(new java.awt.Color(255, 255, 255));
        enrollA.setText("Admin");
        enrollA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enrollA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enrollAMouseMoved(evt);
            }
        });
        enrollA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollAActionPerformed(evt);
            }
        });
        hmpnl.add(enrollA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 100, 90));

        enroll.setBackground(new java.awt.Color(102, 102, 255));
        enroll.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enroll.setForeground(new java.awt.Color(0, 0, 102));
        enroll.setText("Registration");
        enroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enroll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enrollMouseMoved(evt);
            }
        });
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });
        hmpnl.add(enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, 140));

        phonelvl.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        phonelvl.setForeground(new java.awt.Color(0, 0, 102));
        phonelvl.setText("Phone");
        hmpnl.add(phonelvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 200, 30));

        emaillv.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        emaillv.setForeground(new java.awt.Color(0, 0, 102));
        emaillv.setText("Email");
        hmpnl.add(emaillv, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 200, 30));

        namelvl.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        namelvl.setForeground(new java.awt.Color(0, 0, 102));
        namelvl.setText("Name");
        hmpnl.add(namelvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 200, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setText("Edit Profile");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hmpnl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 153, 90, 20));

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addComponent(hmpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hmpnl, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        home.add(HomePanel, "card3");

        StudentPanel.setBackground(new java.awt.Color(255, 255, 255));
        StudentPanel.setMaximumSize(new java.awt.Dimension(842, 308));
        StudentPanel.setMinimumSize(new java.awt.Dimension(842, 308));

        stupnl.setBackground(new java.awt.Color(255, 255, 255));
        stupnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Student Is Empty");
        stupnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 132, -1, -1));

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stupnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stupnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        home.add(StudentPanel, "card3");

        FacultyPanel.setBackground(new java.awt.Color(255, 255, 255));
        FacultyPanel.setMaximumSize(new java.awt.Dimension(842, 308));
        FacultyPanel.setMinimumSize(new java.awt.Dimension(842, 308));
        FacultyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fclpnl.setBackground(new java.awt.Color(255, 255, 255));
        fclpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Faculty is empty");
        fclpnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 127, -1, -1));

        FacultyPanel.add(fclpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 310));

        home.add(FacultyPanel, "card4");

        departmentPanel.setBackground(new java.awt.Color(255, 255, 255));
        departmentPanel.setMaximumSize(new java.awt.Dimension(842, 308));
        departmentPanel.setMinimumSize(new java.awt.Dimension(842, 308));
        departmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dptpnl.setBackground(new java.awt.Color(255, 255, 255));
        dptpnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dptpnlMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dptpnlMouseMoved(evt);
            }
        });
        dptpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCE.setBackground(new java.awt.Color(51, 0, 255));
        btnCE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCE.setForeground(new java.awt.Color(255, 255, 255));
        btnCE.setText("CE");
        btnCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCEMouseMoved(evt);
            }
        });
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        dptpnl.add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 130, 30));

        btnENG.setBackground(new java.awt.Color(51, 0, 255));
        btnENG.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnENG.setForeground(new java.awt.Color(255, 255, 255));
        btnENG.setText("ENG");
        btnENG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnENG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnENGMouseMoved(evt);
            }
        });
        btnENG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENGActionPerformed(evt);
            }
        });
        dptpnl.add(btnENG, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 130, 30));

        btnEEE.setBackground(new java.awt.Color(51, 0, 255));
        btnEEE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEEE.setForeground(new java.awt.Color(255, 255, 255));
        btnEEE.setText("EEE");
        btnEEE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEEE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEEEMouseMoved(evt);
            }
        });
        btnEEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEEEActionPerformed(evt);
            }
        });
        dptpnl.add(btnEEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 130, 30));

        btnAdd.setBackground(new java.awt.Color(51, 0, 255));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAddMouseMoved(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        dptpnl.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 40));

        btnLAW.setBackground(new java.awt.Color(51, 0, 255));
        btnLAW.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLAW.setForeground(new java.awt.Color(255, 255, 255));
        btnLAW.setText("LAW");
        btnLAW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLAW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLAWMouseMoved(evt);
            }
        });
        btnLAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLAWActionPerformed(evt);
            }
        });
        dptpnl.add(btnLAW, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 130, 30));

        btnBBA.setBackground(new java.awt.Color(51, 0, 255));
        btnBBA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBBA.setForeground(new java.awt.Color(255, 255, 255));
        btnBBA.setText("BBA");
        btnBBA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBBA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBBAMouseMoved(evt);
            }
        });
        btnBBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBAActionPerformed(evt);
            }
        });
        dptpnl.add(btnBBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 130, 30));

        btnCSE.setBackground(new java.awt.Color(51, 0, 255));
        btnCSE.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCSE.setForeground(new java.awt.Color(255, 255, 255));
        btnCSE.setText("CSE");
        btnCSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCSE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCSEMouseMoved(evt);
            }
        });
        btnCSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSEActionPerformed(evt);
            }
        });
        dptpnl.add(btnCSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, 30));

        btnView.setBackground(new java.awt.Color(51, 0, 255));
        btnView.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnViewMouseMoved(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        dptpnl.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 130, 40));

        btnCourses.setBackground(new java.awt.Color(102, 102, 255));
        btnCourses.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCourses.setForeground(new java.awt.Color(0, 0, 102));
        btnCourses.setText("Courses");
        btnCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCourses.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCoursesMouseMoved(evt);
            }
        });
        btnCourses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCoursesFocusGained(evt);
            }
        });
        btnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesActionPerformed(evt);
            }
        });
        dptpnl.add(btnCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 90));

        departmentPanel.add(dptpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 310));

        home.add(departmentPanel, "card4");

        main.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, -1, 308));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        resetLblColor(btnDepartment);
        setLblColor(btnHome);
        resetLblColor(btnFaculty);
        resetLblColor(btnStudent);
        //switch bettween Jpanels
        HomePanel.setVisible(true);
        StudentPanel.setVisible(false);
        FacultyPanel.setVisible(false);
        departmentPanel.setVisible(false);
      
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacultyMouseClicked
        // TODO add your handling code here:
        resetLblColor(btnDepartment);
        setLblColor(btnFaculty);
        resetLblColor(btnHome);
        resetLblColor(btnStudent);
        departmentPanel.setVisible(false);
        FacultyPanel.setVisible(true);
        HomePanel.setVisible(false);
        StudentPanel.setVisible(false);
    }//GEN-LAST:event_btnFacultyMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        resetLblColor(btnDepartment);
        setLblColor(btnStudent);
        resetLblColor(btnHome);
        resetLblColor(btnFaculty);
        departmentPanel.setVisible(false);
        StudentPanel.setVisible(true);
        HomePanel.setVisible(false);
        FacultyPanel.setVisible(false);
    }//GEN-LAST:event_btnStudentMouseClicked

    int xx;
    int xy;
    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        Login c = new Login();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollActionPerformed

    private void enrollMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollMouseMoved
        // TODO add your handling code here:
//        enrollFaculty.setVisible(true);
//        try {
//            TimeUnit.SECONDS.sleep(1);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        enrollStudent.setVisible(true);  
        try
        {
            enrollF.setVisible(true); 
            Thread.sleep(150);
            enrollS.setVisible(true);
            Thread.sleep(150);
            enrollA.setVisible(true);
        }
        catch(InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }
        enrollF.setSize(100, 90);
        enrollS.setSize(100, 90);
        enrollA.setSize(100, 90);
               
        
    }//GEN-LAST:event_enrollMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //For Home section
        enrollF.setVisible(false);
        enrollS.setVisible(false);
        enrollA.setVisible(false);
        
        
        
        //For Department Section
        btnAdd.setVisible(false);
        //......
        btnView.setVisible(false);
        btnCSE.setVisible(false);
        btnEEE.setVisible(false);
        btnCE.setVisible(false);
        btnBBA.setVisible(false);
        btnLAW.setVisible(false);
        btnENG.setVisible(false);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void kGradientPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseMoved
        // TODO add your handling code here:
        enrollF.setVisible(false);
        enrollS.setVisible(false);
        enrollA.setVisible(false);
        
        //For Department Section
        btnAdd.setVisible(false);
        //......
        btnView.setVisible(false);
        btnCSE.setVisible(false);
        btnEEE.setVisible(false);
        btnCE.setVisible(false);
        btnBBA.setVisible(false);
        btnLAW.setVisible(false);
        btnENG.setVisible(false);
    }//GEN-LAST:event_kGradientPanel1MouseMoved

    private void enrollFMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollFMouseMoved
        // TODO add your handling code here:
        enrollF.setVisible(true);
        enrollS.setVisible(true);
        enrollA.setVisible(true);
        
        enrollF.setSize(110, 100);
        //enrollF.setSize(100, 90);

    }//GEN-LAST:event_enrollFMouseMoved

    private void enrollSMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollSMouseMoved
        // TODO add your handling code here:
        enrollF.setVisible(true);
        enrollS.setVisible(true);
        enrollA.setVisible(true);
        
        enrollS.setSize(110, 100);
    }//GEN-LAST:event_enrollSMouseMoved

    private void hmpnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmpnlMouseMoved
        // TODO add your handling code here:
        enrollF.setVisible(false);
        enrollS.setVisible(false);
        enrollA.setVisible(false);
        
    }//GEN-LAST:event_hmpnlMouseMoved

    private void enrollAMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollAMouseMoved
        // TODO add your handling code here:
        enrollF.setVisible(true);
        enrollS.setVisible(true);
        enrollA.setVisible(true);
        
        enrollA.setSize(110, 100);
    }//GEN-LAST:event_enrollAMouseMoved

    private void enrollSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollSActionPerformed
        // TODO add your handling code here:
        regStudent c = new regStudent(sendUser,sendPassword);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enrollSActionPerformed

    private void enrollAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollAActionPerformed
        // TODO add your handling code here:
        regAdmin c = new regAdmin(sendUser,sendPassword);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enrollAActionPerformed

    private void enrollFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollFActionPerformed
        // TODO add your handling code here:
        regFaculty c = new regFaculty(sendUser,sendPassword);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enrollFActionPerformed

    private void btnDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentMouseClicked
        // TODO add your handling code here:
        setLblColor(btnDepartment);
        resetLblColor(btnFaculty);
        resetLblColor(btnHome);
        resetLblColor(btnStudent);
        departmentPanel.setVisible(true);
        FacultyPanel.setVisible(false);
        HomePanel.setVisible(false);
        StudentPanel.setVisible(false);
    }//GEN-LAST:event_btnDepartmentMouseClicked

    private void btnAddMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseMoved

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String flag="add";
        departmentView c = new departmentView(sendUser,sendPassword,flag);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCoursesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoursesMouseMoved
        // TODO add your handling code here:
        try
        {
            btnAdd.setVisible(true); 
            Thread.sleep(150);
            btnView.setVisible(true);
            
            btnCSE.setVisible(false);
            btnEEE.setVisible(false);
            btnBBA.setVisible(false);
            btnCE.setVisible(false);
            btnENG.setVisible(false);
            btnLAW.setVisible(false);
        }
        catch(InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }
//        enrollF.setSize(100, 90);
//        enrollS.setSize(100, 90);
        
    }//GEN-LAST:event_btnCoursesMouseMoved

    private void btnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoursesActionPerformed

    private void btnViewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseMoved
        // TODO add your handling code here:
        try
        {
            Thread.sleep(150);
            btnCSE.setVisible(true); 
            btnBBA.setVisible(true);
            
            btnEEE.setVisible(true);
            btnCE.setVisible(true);
            btnLAW.setVisible(true);
            btnENG.setVisible(true);
        }
        catch(InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }
//        enrollF.setSize(100, 90);
//        enrollS.setSize(100, 90);
    }//GEN-LAST:event_btnViewMouseMoved

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCEMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEMouseMoved

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
//        main.setVisible(false);
//        
//        addCourses.setVisible(false);
//        //viewCourses.setVisible(false);
//        //....
//        viewCoursesCSE.setVisible(false);
//        viewCoursesEEE.setVisible(false);
//        viewCoursesCE.setVisible(true);
//        viewCoursesBBA.setVisible(false);
//        viewCoursesLAW.setVisible(false);
//        viewCoursesENG.setVisible(false);
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCSEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCSEMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCSEMouseMoved

    private void btnCSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSEActionPerformed
        // TODO add your handling code here:
       String flag="CSE";
       departmentView c = new departmentView(sendUser,sendPassword,flag);
       c.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnCSEActionPerformed

    private void btnLAWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLAWMouseMoved
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnLAWMouseMoved

    private void btnLAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLAWActionPerformed
        // TODO add your handling code here:
//        main.setVisible(false);
//        
//        addCourses.setVisible(false);
//        //viewCourses.setVisible(false);
//        //....
//        viewCoursesCSE.setVisible(false);
//        viewCoursesEEE.setVisible(false);
//        viewCoursesCE.setVisible(false);
//        viewCoursesBBA.setVisible(false);
//        viewCoursesLAW.setVisible(true);
//        viewCoursesENG.setVisible(false);
    }//GEN-LAST:event_btnLAWActionPerformed

    private void btnENGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnENGMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnENGMouseMoved

    private void btnENGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENGActionPerformed
        // TODO add your handling code here:
//        main.setVisible(false);
//        
//        addCourses.setVisible(false);
//        //viewCourses.setVisible(false);
//        //....
//        viewCoursesCSE.setVisible(false);
//        viewCoursesEEE.setVisible(false);
//        viewCoursesCE.setVisible(false);
//        viewCoursesBBA.setVisible(false);
//        viewCoursesLAW.setVisible(false);
//        viewCoursesENG.setVisible(true);
    }//GEN-LAST:event_btnENGActionPerformed

    private void btnEEEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEEEMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEEEMouseMoved

    private void btnEEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEEEActionPerformed
        // TODO add your handling code here:
       String flag="EEE";
       departmentView c = new departmentView(sendUser,sendPassword,flag);
       c.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_btnEEEActionPerformed

    private void btnBBAMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBBAMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBBAMouseMoved

    private void btnBBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBAActionPerformed
        // TODO add your handling code here:
//        main.setVisible(false);
//        
//        addCourses.setVisible(false);
//        //viewCourses.setVisible(false);
//        //....
//        viewCoursesCSE.setVisible(false);
//        viewCoursesEEE.setVisible(false);
//        viewCoursesCE.setVisible(false);
//        viewCoursesBBA.setVisible(true);
//        viewCoursesLAW.setVisible(false);
//        viewCoursesENG.setVisible(false);
    }//GEN-LAST:event_btnBBAActionPerformed

    private void dptpnlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dptpnlMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_dptpnlMouseDragged

    private void dptpnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dptpnlMouseMoved
        // TODO add your handling code here:
        //For Department Section
        btnAdd.setVisible(false);
        //......
        btnView.setVisible(false);
        btnCSE.setVisible(false);
        btnEEE.setVisible(false);
        btnCE.setVisible(false);
        btnBBA.setVisible(false);
        btnLAW.setVisible(false);
        btnENG.setVisible(false);
    }//GEN-LAST:event_dptpnlMouseMoved

    private void btnCoursesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCoursesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoursesFocusGained
    
    // ------------switch between colors for Active/Inactive color
    public void setLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(51,0,204)); //deep
    }
    
      public void resetLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(51,102,255)); //light
    }
      
           
      
      //-----------End --------
      
     //Let's create staff options and Avoid data
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //Change UI look of table.
        System.out.println("Main Function in Dashboard");
//        try
//        {
//            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//        } catch(Exception ex)
//        {
//
//        }

        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FacultyPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel USERIMAGE;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBBA;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCSE;
    private javax.swing.JButton btnCourses;
    private javax.swing.JLabel btnDepartment;
    private javax.swing.JButton btnEEE;
    private javax.swing.JButton btnENG;
    private javax.swing.JLabel btnFaculty;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnLAW;
    private javax.swing.JLabel btnStudent;
    private javax.swing.JLabel btnStudent4;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel departmentPanel;
    private javax.swing.JPanel dptpnl;
    private javax.swing.JLabel emaillv;
    private javax.swing.JButton enroll;
    private javax.swing.JButton enrollA;
    private javax.swing.JButton enrollF;
    private javax.swing.JButton enrollS;
    private javax.swing.JPanel fclpnl;
    private javax.swing.JPanel hmpnl;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton logout;
    private javax.swing.JPanel main;
    private javax.swing.JLabel namelvl;
    private javax.swing.JLabel phonelvl;
    private javax.swing.JPanel stupnl;
    // End of variables declaration//GEN-END:variables
    private String department;
}
