
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import keeptoo.Drag;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Imrul
 */
public class Login extends javax.swing.JFrame {
    //System.exit(0);
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    //visible password
    int swt=0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = uapDB.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        comboSelect = new javax.swing.JComboBox<>();
        forgetPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        setUndecorated(true);

        kGradientPanel1.setForeground(new java.awt.Color(255, 102, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setBackground(new Color(0, 0, 0, 0));
        userField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 255, 255));
        userField.setText("imrulhasan273");
        userField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        userField.setCaretColor(new java.awt.Color(255, 0, 204));
        userField.setOpaque(false);
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 380, 40));

        passField.setBackground(new Color(0, 0, 0, 0));
        passField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setText("imrul");
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        passField.setCaretColor(new java.awt.Color(255, 0, 204));
        passField.setOpaque(false);
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 380, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uaplogo1.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 130, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_groups_64px.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 70, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_2_64px.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 60, 50));

        alert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(204, 0, 51));
        kGradientPanel1.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 370, 30));

        comboSelect.setForeground(new java.awt.Color(0, 0, 153));
        comboSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "Item 3", "Item 4" }));
        comboSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        forgetPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        forgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        forgetPassword.setText("Forget Password?");
        forgetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordMouseClicked(evt);
            }
        });
        kGradientPanel1.add(forgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 100, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log In");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_26px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, 20));

        jButton2.setText("email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_passFieldActionPerformed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        //drag here
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:
        //grab
        
    }//GEN-LAST:event_kGradientPanel1KeyPressed
    int xx;
    int xy;
    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel1).onPress(evt);
        xx = evt.getX();
        xy = evt.getY();
        //use mouse always
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_userFieldActionPerformed

    private void comboSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String auser = userField.getText();
        String apass = passField.getText();
        if (userField.getText().equals("")) 
        {
            alert.setText("User field is empty!");            
        }
        else if (passField.getText().equals("")) {
            alert.setText("Password field is empty!");
        }
        else
        {
            String sql = "select * from admin where username = '"+auser+"' and password = '"+apass+"' ";
            try
            {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                System.out.println("login: "+rs+"login");
                if (rs.next()) 
                {
                    rs.close();
                    pst.close();
                    //close(); // and set Default close operation to DISPOSE from EXIT ON CLOSE
                    
                    
                    //new frame to open-----------------------------------------
                    String Option;
                    Option = comboSelect.getSelectedItem().toString();
                    System.out.println("Combo: "+Option);
                    
                    if("admin".equals(Option))
                    {
//                                try
//                                {
//                                  UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//                                } catch(Exception ex)
//                                 {
//
//                                 }
                        dashboard c = new dashboard(auser,apass);
                        c.setVisible(true);
                        this.setVisible(false);
                    }
                    else if("student".equals(Option))
                    {
                        //
                    }
                    else if("faculty".equals(Option))
                    {
                        //
                    }
                    else
                    {
                        alert.setText("Choose the Option properly!");
                    }
                    //////--------------------------------------
                    
                    
                    //////--------------------------------------
                    
                    
                    System.out.print("END");
                } else 
                {
                    alert.setText("Username or Password is incorrect!");
                    alert.setBackground(Color.RED);
                    //passField.setBackground(Color.RED);
                }
            }
            catch (Exception e)
            {
                System.out.print("OUT");
                JOptionPane.showMessageDialog(null, e);
            }
            finally 
            {
                try 
                {
                    rs.close();
                    pst.close();
                    //conn.close();
                } 
                catch (Exception e) 
                {
                    //
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void forgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordMouseClicked
        // TODO add your handling code here:
        //setForeground(new Color(0,204,51));
        setLblColor(forgetPassword);
    }//GEN-LAST:event_forgetPasswordMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(swt==0)
        {
            passField.setEchoChar((char)0);
            swt=swt+1;
        }
        else
        {
            passField.setEchoChar('*');
            swt=swt-1;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        emailCheck c = new emailCheck();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setLblColor(JLabel lbl)
    {
        lbl.setForeground(new Color(0,204,51)); //deep
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //____________________________________________________________________________________________________________________________
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch(Exception ex)
        {
            
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JComboBox<String> comboSelect;
    private javax.swing.JLabel forgetPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
