/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Imrul
 */
public class regFaculty extends javax.swing.JFrame {

    /**
     * Creates new form regAdmin
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    //2 switches to visible text in password field.
    int swt=0;
    int swt2=0;
    
    String userAdmin;
    String passAdmin;
    public regFaculty() {
        initComponents();
    }
    
    String ImgPath = null;
    //...............cut

    //Extend Construction made from dashboard form
    public regFaculty(String sendUser, String sendPassword) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        conn = uapDB.connectDB(); 
        regFaculties.setFocusable(true);         //it is used to unfocus initially
        
        
        userAdmin=sendUser;
        passAdmin=sendPassword;
        System.out.println(sendUser);
        System.out.println(sendPassword);
    }
    
    //Checking empty inputs
    public boolean checkInputs()
    {
        if(userField.getText().trim().toLowerCase().equals("type username") 
                || nameField.getText().trim().toLowerCase().equals("type name") 
                || passField.getText().trim().toLowerCase().equals("type password") 
                || passField2.getText().trim().toLowerCase().equals("type password") 
                || emailField.getText().trim().toLowerCase().equals("type email") 
                || phoneField.getText().trim().toLowerCase().equals("type phone")
                || idField.getText().trim().toLowerCase().equals("type ID")
          ) 
        {
            return false;
        }
        else
        {
            try {
                return true;
            } catch (Exception ex) {
                return false;
            }
        }
    }
    
    
    // Resize Image
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }
        else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(imageShow.getWidth(), imageShow.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regFaculties = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        passField2 = new javax.swing.JPasswordField();
        passField = new javax.swing.JPasswordField();
        imageShow = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        imageChoose = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        warnField = new javax.swing.JLabel();
        visiblePass2 = new javax.swing.JLabel();
        visiblePass1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bba = new javax.swing.JRadioButton();
        cse = new javax.swing.JRadioButton();
        eee = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regFaculties.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Faculty registration");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UAP");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_male_40px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        regFaculties.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 860, 63));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Department:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Re-Password:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Photo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Password: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, 30));

        nameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(204, 204, 204));
        nameField.setText("Type name");
        nameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFieldMouseClicked(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 340, 30));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.setText("Type email");
        emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 340, 30));

        phoneField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneField.setForeground(new java.awt.Color(204, 204, 204));
        phoneField.setText("Type phone");
        phoneField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFieldFocusLost(evt);
            }
        });
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        jPanel2.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 340, 30));

        userField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userField.setForeground(new java.awt.Color(204, 204, 204));
        userField.setText("Type username");
        userField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        userField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFieldFocusLost(evt);
            }
        });
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFieldMouseClicked(evt);
            }
        });
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        jPanel2.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 340, 30));

        passField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passField2.setForeground(new java.awt.Color(204, 204, 204));
        passField2.setText("Type password");
        passField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        passField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passField2FocusLost(evt);
            }
        });
        passField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passField2ActionPerformed(evt);
            }
        });
        jPanel2.add(passField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 340, 30));

        passField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.setText("Type password");
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 340, 30));

        imageShow.setBackground(new java.awt.Color(247, 244, 244));
        imageShow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imageShow.setForeground(new java.awt.Color(255, 0, 0));
        imageShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageShow.setOpaque(true);
        jPanel2.add(imageShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 150, 130));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 80, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registration");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 100, 30));

        imageChoose.setBackground(new java.awt.Color(229, 214, 214));
        imageChoose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imageChoose.setText("Choose Image");
        imageChoose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imageChoose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imageChoose.setOpaque(true);
        imageChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageChooseMouseClicked(evt);
            }
        });
        jPanel2.add(imageChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 90, 20));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 860, 10));

        warnField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        warnField.setForeground(new java.awt.Color(255, 51, 0));
        jPanel2.add(warnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 410, 30));

        visiblePass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_16px.png"))); // NOI18N
        visiblePass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visiblePass2MouseClicked(evt);
            }
        });
        jPanel2.add(visiblePass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 20, 30));

        visiblePass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_16px.png"))); // NOI18N
        visiblePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visiblePass1MouseClicked(evt);
            }
        });
        jPanel2.add(visiblePass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 20, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Username: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, 30));

        bba.setBackground(new java.awt.Color(255, 255, 255));
        bba.setText("BBA");
        bba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbaActionPerformed(evt);
            }
        });
        jPanel2.add(bba, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 60, -1));

        cse.setBackground(new java.awt.Color(255, 255, 255));
        cse.setText("CSE");
        cse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cseActionPerformed(evt);
            }
        });
        jPanel2.add(cse, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 60, -1));

        eee.setBackground(new java.awt.Color(255, 255, 255));
        eee.setText("EEE");
        eee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeeActionPerformed(evt);
            }
        });
        jPanel2.add(eee, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Name:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 30));

        idField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idField.setForeground(new java.awt.Color(204, 204, 204));
        idField.setText("Type ID");
        idField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 153)));
        idField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFieldFocusLost(evt);
            }
        });
        idField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idFieldMouseClicked(evt);
            }
        });
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel2.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 210, 30));

        regFaculties.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 450));

        getContentPane().add(regFaculties, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:   
        dashboard c = null;
        try {
            c = new dashboard(userAdmin,passAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(regAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && ImgPath!=null)
        {
            ///***************** Flag to verify if user length is limited *****
            String usr=userField.getText();
            int lens = usr.length();
            System.out.println(lens);
            boolean validLengthUser = false;
            if(lens>=5 && lens<=18)
            {
                validLengthUser = true;
            }
            ////________________________________________________________________
            
            
            ///***************** Flag to verify if pass length is limited *****
            String pass=passField.getText();
            int len = pass.length();
            System.out.println(len);
            boolean validLength = false;
            if(len>=6 && len<=18)
            {
                validLength = true;
            }
            ////________________________________________________________________
            
            ///**********  Flag to ensure at least 1 digit and 1 char in password text field  ***********************************
            String st=passField.getText();
            boolean containsDigit = false;
            boolean containsChar = false;
            boolean ContainsMixed = false;
            if (st != null && !st.isEmpty()) 
            {
                for (char c : st.toCharArray()) 
                {
                    if (Character.isDigit(c)) 
                    {
                        containsDigit=true;
                    }

                    if (Character.isLetter(c))
                    {
                        containsChar=true;
                    }
                }
            }
            if(containsDigit && containsChar)
            {
                ContainsMixed = true;
            }
            ///_________________________________________________________________________
            
            
            ///flag phone number is numeric or not___________
            String string = phoneField.getText();
            boolean numeric = true;
            try 
            {
                Double num = Double.parseDouble(string);
            } 
            catch (NumberFormatException e) 
            {
                numeric = false;
            }
            ///_________________________________________________

            warnField.setText("");
            if(validLengthUser && passField.getText().equals(passField2.getText()) && validLength && ContainsMixed && emailField.getText().contains("@") && numeric)
            {
                InputStream img = null;
                try{
                    String s=new String();

                    String a= userField.getText();
                    String b= nameField.getText();
                    String c= passField.getText();
                    String d= phoneField.getText();
                    String e= emailField.getText().toLowerCase();    
                    String f= idField.getText();
                    String g= department;

                    // the mysql insert statement
                    img = new FileInputStream(new File(ImgPath));
                    String query = "INSERT into faculties(username, name, password, phone, email, id, department, photo) values (?, ?, ?, ?, ?, ?, ?, ?)";

                    // create the mysql insert preparedstatement
                    pst = conn.prepareStatement(query);

                    pst.setString(1, a);
                    pst.setString(2, b);
                    pst.setString(3, c);
                    pst.setString(4, d);
                    pst.setString(5, e);
                    pst.setString(6, f);
                    pst.setString(7, g);
                    pst.setBlob(8, img); 
                    pst.execute();
                    System.out.println("Successful");
                    warnField.setForeground(Color.green);
                    warnField.setText("Successfully Registered!");
                    
                    ///*****************************************************************************
                    //Go back to make default view of reg page
                    userField.setText("Type username");
                    userField.setForeground(new Color(204,204,204));
                    nameField.setText("Type name");
                    nameField.setForeground(new Color(204,204,204));
                    passField.setText("Type password");
                    passField.setForeground(new Color(204,204,204));
                    passField2.setText("Type password");
                    passField2.setForeground(new Color(204,204,204));
                    emailField.setText("Type email");
                    emailField.setForeground(new Color(204,204,204));
                    phoneField.setText("Type phone");
                    phoneField.setForeground(new Color(204,204,204));
                    idField.setText("Type ID");
                    idField.setForeground(new Color(204,204,204));
                    cse.setSelected(false);
                    eee.setSelected(false);
                    bba.setSelected(false);
                    imageShow.setIcon(null);
                    ///*******************************************************************
                }
                catch(Exception e){
                    System.out.println("Unsuccessful");
                    warnField.setForeground(Color.red);
                    warnField.setText("Unsername or ID already exist!");
                }
                finally
                {
                    try{
                        rs.close();
                        pst.close();
                    }
                    catch(Exception e){
                    }
                }
            }
            else if(!validLengthUser)
            {
                warnField.setForeground(Color.red);
                warnField.setText("Username should be 5 to 18 charecters long!");
            }
            else if(!passField.getText().equals(passField2.getText()))
            {
                warnField.setForeground(Color.red);
                warnField.setText("Passwords should be matched!!!");
            }
            else if(!validLength)
            {
                warnField.setForeground(Color.red);
                warnField.setText("Password should be 6 to 18 charecters long!");
            }
            else if(!ContainsMixed)
            {
                warnField.setForeground(Color.red);
                warnField.setText("Password should contain at least one digit and one char!!!");
            }
            
            else if(!emailField.getText().contains("@"))
            {
                warnField.setForeground(Color.red);
                warnField.setText("Invalid email address!!!");
            }    
            else if(!numeric)
            {
                warnField.setForeground(Color.red);
                warnField.setText("Invalid phone number!!!");
            }
      }
      else
      {
          System.out.println("One or more field is empty");  
          warnField.setText("One or more field is empty!!!");
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void imageChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageChooseMouseClicked
        // TODO add your handling code here:        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imageShow.setIcon(ResizeImage(path,null));
            ImgPath = path;
        }
        else
        {
            System.out.println("No file Selected");
        }
    }//GEN-LAST:event_imageChooseMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void nameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFieldMouseClicked
        
    }//GEN-LAST:event_nameFieldMouseClicked

    private void userFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFieldMouseClicked

    }//GEN-LAST:event_userFieldMouseClicked

    private void userFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusGained
        // TODO add your handling code here:
         if(userField.getText().trim().toLowerCase().equals("type username")){
            userField.setText("");
            userField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userFieldFocusGained

    private void userFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusLost
        // TODO add your handling code here:
         if(userField.getText().trim().equals("")){
            userField.setText("Type username");
            userField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_userFieldFocusLost

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
        if(nameField.getText().trim().toLowerCase().equals("type name")){
            nameField.setText("");
            nameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void passField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passField2ActionPerformed
        // TODO add your handling code here:
        if(passField.getText().trim().toLowerCase().equals("Type password")){
            passField.setText("");
            passField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passField2ActionPerformed

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        if(nameField.getText().trim().equals("")){
            nameField.setText("Type name");
            nameField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        if(passField.getText().trim().toLowerCase().equals("type password")){
            passField.setText("");
            passField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        // TODO add your handling code here:
        if(passField.getText().trim().equals("")){
            passField.setText("Type password");
            passField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void passField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField2FocusGained
        // TODO add your handling code here:
        if(passField2.getText().trim().toLowerCase().equals("type password")){
            passField2.setText("");
            passField2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passField2FocusGained

    private void passField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField2FocusLost
        // TODO add your handling code here:
        if(passField2.getText().trim().equals("")){
            passField2.setText("Type password");
            passField2.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_passField2FocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if(emailField.getText().trim().toLowerCase().equals("type email")){
            emailField.setText("");
            emailField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(emailField.getText().trim().equals("")){
            emailField.setText("Type email");
            emailField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
        // TODO add your handling code here:
        if(phoneField.getText().trim().toLowerCase().equals("type phone")){
            phoneField.setText("");
            phoneField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_phoneFieldFocusGained

    private void phoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusLost
        // TODO add your handling code here:
        if(phoneField.getText().trim().equals("")){
            phoneField.setText("Type phone");
            phoneField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_phoneFieldFocusLost

    private void visiblePass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiblePass2MouseClicked
        // TODO add your handling code here:
        
        if(swt2==0)
        {
            passField2.setEchoChar((char)0);
            swt2=swt2+1;
        }
        else
        {
            passField2.setEchoChar('*');
            swt2=swt2-1;
        }
    }//GEN-LAST:event_visiblePass2MouseClicked

    private void visiblePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiblePass1MouseClicked
        // TODO add your handling code here:
        if(swt==0)
        {
            passField.setEchoChar((char)0);
            swt=swt+1;
        }
        else
        {
            passField.setEchoChar('*');
            swt=swt-1;
        }
    }//GEN-LAST:event_visiblePass1MouseClicked

    private void eeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeeActionPerformed
        // TODO add your handling code here:
        department="EEE";
        cse.setSelected(false);
        eee.setSelected(true);
        bba.setSelected(false);
    }//GEN-LAST:event_eeeActionPerformed

    private void bbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbaActionPerformed
        // TODO add your handling code here:
        department="BBA";
        cse.setSelected(false);
        eee.setSelected(false);
        bba.setSelected(true);
    }//GEN-LAST:event_bbaActionPerformed

    private void idFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusGained
        // TODO add your handling code here:
        if(idField.getText().trim().toLowerCase().equals("type id")){
            idField.setText("");
            idField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_idFieldFocusGained

    private void idFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusLost
        // TODO add your handling code here:
        if(idField.getText().trim().equals("")){
            idField.setText("Type ID");
            idField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_idFieldFocusLost

    private void idFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldMouseClicked

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void cseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cseActionPerformed
        // TODO add your handling code here:
        department="CSE";
        cse.setSelected(true);
        eee.setSelected(false);
        bba.setSelected(false);
    }//GEN-LAST:event_cseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bba;
    private javax.swing.JRadioButton cse;
    private javax.swing.JRadioButton eee;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel imageChoose;
    private javax.swing.JLabel imageShow;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPasswordField passField2;
    private javax.swing.JTextField phoneField;
    private javax.swing.JPanel regFaculties;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel visiblePass1;
    private javax.swing.JLabel visiblePass2;
    private javax.swing.JLabel warnField;
    // End of variables declaration//GEN-END:variables
    private String department;
}
